
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nvwremdichzzmcvjyhjd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im52d3JlbWRpY2h6em1jdmp5aGpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNDQ0MDQsImV4cCI6MjA2MDYyMDQwNH0.3CHGfqezAksO5IX81f6UTTrhiIecJMlHr0fbKqayv0A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Define the type for tables not yet in the Database type
type CustomDatabase = Database & {
  public: {
    Tables: {
      profiles: Database['public']['Tables']['profiles'];
      ao_locations: {
        Row: {
          id: string;
          name: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          created_at?: string;
        };
      };
      hotspots: {
        Row: {
          id: string;
          name: string;
          ao_location_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          ao_location_id: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          ao_location_id?: string;
          created_at?: string;
        };
      };
      risk_scores: {
        Row: {
          id: string;
          respondent_type: string;
          score: number;
          phase: number;
          hotspot_id: string;
          data_completeness: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          respondent_type: string;
          score: number;
          phase: number;
          hotspot_id: string;
          data_completeness: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          respondent_type?: string;
          score?: number;
          phase?: number;
          hotspot_id?: string;
          data_completeness?: number;
          created_at?: string;
        };
      };
      detailed_metrics: {
        Row: {
          id: string;
          risk_score_id: string;
          metric_name: string;
          score: number;
          likelihood: number;
          severity: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          risk_score_id: string;
          metric_name: string;
          score: number;
          likelihood: number;
          severity: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          risk_score_id?: string;
          metric_name?: string;
          score?: number;
          likelihood?: number;
          severity?: number;
          created_at?: string;
        };
      };
    };
  };
};

export const supabase = createClient<CustomDatabase>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    storage: localStorage
  }
});
